import type { OxlintConfig } from "oxlint";

const config: OxlintConfig = {
  options: {
    typeAware: true,
    typeCheck: true,
    reportUnusedDisableDirectives: "warn",
  },
  plugins: ["oxc", "eslint", "unicorn", "typescript", "import"],
  rules: {
    // #region oxc
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/approx-constant
    "oxc/approx-constant": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/bad-bitwise-operator
    "oxc/bad-bitwise-operator": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/branches-sharing-code
    "oxc/branches-sharing-code": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/misrefactored-assign-op
    "oxc/misrefactored-assign-op": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/no-accumulating-spread
    "oxc/no-accumulating-spread": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/no-barrel-file
    "oxc/no-barrel-file": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/no-const-enum
    "oxc/no-const-enum": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/no-map-spread
    "oxc/no-map-spread": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/oxc/no-this-in-exported-function
    "oxc/no-this-in-exported-function": "warn",
    // #endregion

    // #region eslint
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/accessor-pairs
    "accessor-pairs": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/array-callback-return
    "array-callback-return": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/default-case-last
    "default-case-last": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/default-param-last
    "default-param-last": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/eqeqeq
    eqeqeq: "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/func-names
    "func-names": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/grouped-accessor-pairs
    "grouped-accessor-pairs": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/new-cap
    "new-cap": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-array-constructor
    "no-array-constructor": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-await-in-loop
    "no-await-in-loop": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-case-declarations
    "no-case-declarations": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-constructor-return
    "no-constructor-return": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-duplicate-imports
    "no-duplicate-imports": ["warn", { allowSeparateTypeImports: true }],
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-else-return
    "no-else-return": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-empty
    "no-empty": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-empty-function
    "no-empty-function": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-extend-native
    "no-extend-native": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-extra-bind
    "no-extra-bind": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-fallthrough
    "no-fallthrough": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-implicit-coercion
    "no-implicit-coercion": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-labels
    "no-labels": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-lonely-if
    "no-lonely-if": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-loop-func
    "no-loop-func": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-multi-assign
    "no-multi-assign": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-multi-str
    "no-multi-str": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-new
    "no-new": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-new-func
    "no-new-func": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-object-constructor
    "no-object-constructor": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-param-reassign
    "no-param-reassign": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-promise-executor-return
    "no-promise-executor-return": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-proto
    "no-proto": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-return-assign
    "no-return-assign": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-script-url
    "no-script-url": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-self-compare
    "no-self-compare": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-sequences
    "no-sequences": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-template-curly-in-string
    "no-template-curly-in-string": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-underscore-dangle
    "no-underscore-dangle": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-unmodified-loop-condition
    "no-unmodified-loop-condition": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-unneeded-ternary
    "no-unneeded-ternary": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-use-before-define
    "no-use-before-define": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-useless-assignment
    "no-useless-assignment": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-useless-call
    "no-useless-call": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-useless-computed-key
    "no-useless-computed-key": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-useless-concat
    "no-useless-concat": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-useless-constructor
    "no-useless-constructor": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-useless-return
    "no-useless-return": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-var
    "no-var": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-warning-comments
    "no-warning-comments": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/operator-assignment
    "operator-assignment": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/prefer-arrow-callback
    "prefer-arrow-callback": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/prefer-const
    "prefer-const": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/prefer-numeric-literals
    "prefer-numeric-literals": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/prefer-object-has-own
    "prefer-object-has-own": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/prefer-object-spread
    "prefer-object-spread": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/prefer-rest-params
    "prefer-rest-params": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/prefer-spread
    "prefer-spread": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/preserve-caught-error
    "preserve-caught-error": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/radix
    radix: "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/symbol-description
    "symbol-description": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/unicode-bom
    "unicode-bom": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/eslint/yoda
    yoda: "warn",
    // #endregion

    // #region unicorn
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/catch-error-name
    "unicorn/catch-error-name": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/consistent-date-clone
    "unicorn/consistent-date-clone": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/consistent-function-scoping
    "unicorn/consistent-function-scoping": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/consistent-template-literal-escape
    "unicorn/consistent-template-literal-escape": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/custom-error-definition
    "unicorn/custom-error-definition": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/error-message
    "unicorn/error-message": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/explicit-length-check
    "unicorn/explicit-length-check": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/new-for-builtins
    "unicorn/new-for-builtins": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-abusive-eslint-disable
    "unicorn/no-abusive-eslint-disable": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-accessor-recursion
    "unicorn/no-accessor-recursion": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-array-fill-with-reference-type
    "unicorn/no-array-fill-with-reference-type": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-array-for-each
    "unicorn/no-array-for-each": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-array-method-this-argument
    "unicorn/no-array-method-this-argument": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-await-expression-member
    "unicorn/no-await-expression-member": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-console-spaces
    "unicorn/no-console-spaces": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-document-cookie
    "unicorn/no-document-cookie": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-immediate-mutation
    "unicorn/no-immediate-mutation": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-instanceof-builtins
    "unicorn/no-instanceof-builtins": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-length-as-slice-end
    "unicorn/no-length-as-slice-end": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-lonely-if
    "unicorn/no-lonely-if": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-magic-array-flat-depth
    "unicorn/no-magic-array-flat-depth": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-negation-in-equality-check
    "unicorn/no-negation-in-equality-check": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-new-buffer
    "unicorn/no-new-buffer": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-object-as-default-parameter
    "unicorn/no-object-as-default-parameter": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-typeof-undefined
    "unicorn/no-typeof-undefined": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-unnecessary-array-flat-depth
    "unicorn/no-unnecessary-array-flat-depth": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-unnecessary-array-splice-count
    "unicorn/no-unnecessary-array-splice-count": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-unnecessary-slice-end
    "unicorn/no-unnecessary-slice-end": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-useless-collection-argument
    "unicorn/no-useless-collection-argument": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-useless-error-capture-stack-trace
    "unicorn/no-useless-error-capture-stack-trace": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-useless-iterator-to-array
    "unicorn/no-useless-iterator-to-array": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/no-useless-promise-resolve-reject
    "unicorn/no-useless-promise-resolve-reject": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/numeric-separators-style
    "unicorn/numeric-separators-style": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-add-event-listener
    "unicorn/prefer-add-event-listener": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-array-find
    "unicorn/prefer-array-find": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-array-flat
    "unicorn/prefer-array-flat": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-array-flat-map
    "unicorn/prefer-array-flat-map": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-array-index-of
    "unicorn/prefer-array-index-of": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-array-some
    "unicorn/prefer-array-some": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-bigint-literals
    "unicorn/prefer-bigint-literals": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-blob-reading-methods
    "unicorn/prefer-blob-reading-methods": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-classlist-toggle
    "unicorn/prefer-classlist-toggle": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-code-point
    "unicorn/prefer-code-point": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-date-now
    "unicorn/prefer-date-now": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-default-parameters
    "unicorn/prefer-default-parameters": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-dom-node-append
    "unicorn/prefer-dom-node-append": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-dom-node-dataset
    "unicorn/prefer-dom-node-dataset": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-dom-node-remove
    "unicorn/prefer-dom-node-remove": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-dom-node-text-content
    "unicorn/prefer-dom-node-text-content": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-export-from
    "unicorn/prefer-export-from": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-global-this
    "unicorn/prefer-global-this": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-includes
    "unicorn/prefer-includes": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-keyboard-event-key
    "unicorn/prefer-keyboard-event-key": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-logical-operator-over-ternary
    "unicorn/prefer-logical-operator-over-ternary": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-math-min-max
    "unicorn/prefer-math-min-max": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-math-trunc
    "unicorn/prefer-math-trunc": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-modern-dom-apis
    "unicorn/prefer-modern-dom-apis": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-native-coercion-functions
    "unicorn/prefer-native-coercion-functions": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-negative-index
    "unicorn/prefer-negative-index": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-node-protocol
    "unicorn/prefer-node-protocol": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-number-properties
    "unicorn/prefer-number-properties": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-object-from-entries
    "unicorn/prefer-object-from-entries": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-optional-catch-binding
    "unicorn/prefer-optional-catch-binding": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-query-selector
    "unicorn/prefer-query-selector": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-regexp-test
    "unicorn/prefer-regexp-test": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-response-static-json
    "unicorn/prefer-response-static-json": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-single-call
    "unicorn/prefer-single-call": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-string-raw
    "unicorn/prefer-string-raw": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-string-replace-all
    "unicorn/prefer-string-replace-all": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-string-slice
    "unicorn/prefer-string-slice": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-string-trim-start-end
    "unicorn/prefer-string-trim-start-end": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-structured-clone
    "unicorn/prefer-structured-clone": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-ternary
    "unicorn/prefer-ternary": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/prefer-type-error
    "unicorn/prefer-type-error": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/require-array-join-separator
    "unicorn/require-array-join-separator": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/require-module-attributes
    "unicorn/require-module-attributes": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/require-number-to-fixed-digits-argument
    "unicorn/require-number-to-fixed-digits-argument": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/require-post-message-target-origin
    "unicorn/require-post-message-target-origin": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/text-encoding-identifier-case
    "unicorn/text-encoding-identifier-case": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/unicorn/throw-new-error
    "unicorn/throw-new-error": "warn",
    // #endregion

    // #region typescript
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/adjacent-overload-signatures
    "typescript/adjacent-overload-signatures": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/array-type
    "typescript/array-type": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/ban-ts-comment
    "typescript/ban-ts-comment": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/ban-tslint-comment
    "typescript/ban-tslint-comment": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/consistent-generic-constructors
    "typescript/consistent-generic-constructors": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/consistent-type-assertions
    "typescript/consistent-type-assertions": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/consistent-type-definitions
    "typescript/consistent-type-definitions": ["warn", "type"],
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/consistent-type-exports
    "typescript/consistent-type-exports": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/consistent-type-imports
    "typescript/consistent-type-imports": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/dot-notation
    "typescript/dot-notation": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-confusing-non-null-assertion
    "typescript/no-confusing-non-null-assertion": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-confusing-void-expression
    "typescript/no-confusing-void-expression": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-deprecated
    "typescript/no-deprecated": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-dynamic-delete
    "typescript/no-dynamic-delete": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-empty-interface
    "typescript/no-empty-interface": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-empty-object-type
    "typescript/no-empty-object-type": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-explicit-any
    "typescript/no-explicit-any": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-extraneous-class
    "typescript/no-extraneous-class": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-implied-eval
    "typescript/no-implied-eval": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-import-type-side-effects
    "typescript/no-import-type-side-effects": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-invalid-void-type
    "typescript/no-invalid-void-type": ["error", { allowAsThisParameter: true }],
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-misused-promises
    "typescript/no-misused-promises": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-mixed-enums
    "typescript/no-mixed-enums": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-namespace
    "typescript/no-namespace": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-non-null-asserted-nullish-coalescing
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-non-null-assertion
    "typescript/no-non-null-assertion": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-unnecessary-condition
    "typescript/no-unnecessary-condition": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-unnecessary-qualifier
    "typescript/no-unnecessary-qualifier": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-unnecessary-template-expression
    "typescript/no-unnecessary-template-expression": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-unnecessary-type-constraint
    "typescript/no-unnecessary-type-constraint": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-unnecessary-type-conversion
    "typescript/no-unnecessary-type-conversion": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-unnecessary-type-parameters
    "typescript/no-unnecessary-type-parameters": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-unsafe-enum-comparison
    "typescript/no-unsafe-enum-comparison": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/no-unsafe-function-type
    "typescript/no-unsafe-function-type": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/non-nullable-type-assertion-style
    "typescript/non-nullable-type-assertion-style": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/only-throw-error
    "typescript/only-throw-error": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-for-of
    "typescript/prefer-for-of": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-function-type
    "typescript/prefer-function-type": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-literal-enum-member
    "typescript/prefer-literal-enum-member": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-nullish-coalescing
    "typescript/prefer-nullish-coalescing": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-optional-chain
    "typescript/prefer-optional-chain": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-promise-reject-errors
    "typescript/prefer-promise-reject-errors": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-readonly
    "typescript/prefer-readonly": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-reduce-type-parameter
    "typescript/prefer-reduce-type-parameter": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-return-this-type
    "typescript/prefer-return-this-type": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/prefer-string-starts-ends-with
    "typescript/prefer-string-starts-ends-with": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/promise-function-async
    "typescript/promise-function-async": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/require-await
    "typescript/require-await": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/strict-boolean-expressions
    "typescript/strict-boolean-expressions": [
      "warn",
      { allowNullableBoolean: true, allowNumber: false, allowString: false },
    ],
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/switch-exhaustiveness-check
    "typescript/switch-exhaustiveness-check": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/unified-signatures
    "typescript/unified-signatures": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/typescript/use-unknown-in-catch-callback-variable
    "typescript/use-unknown-in-catch-callback-variable": "error",
    // #endregion

    // #region import
    // https://oxc.rs/docs/guide/usage/linter/rules/import/consistent-type-specifier-style
    "import/consistent-type-specifier-style": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/export
    "import/export": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/first
    "import/first": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/no-absolute-path
    "import/no-absolute-path": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/no-anonymous-default-export
    "import/no-anonymous-default-export": "error",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/no-cycle
    "import/no-cycle": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/no-empty-named-blocks
    "import/no-empty-named-blocks": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/no-mutable-exports
    "import/no-mutable-exports": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/no-self-import
    "import/no-self-import": "warn",
    // https://oxc.rs/docs/guide/usage/linter/rules/import/unambiguous
    "import/unambiguous": "warn",
    // #endregion
  },

  overrides: [
    {
      files: ["**/*.{ts,tsx}"],
      rules: {
        "no-const-assign": "off",
      },
    },
    {
      files: ["**/*.{cjs,cts}"],
      rules: {
        "import/unambiguous": "off",
      },
    },
  ],
} satisfies OxlintConfig;

export default config;
